apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-zdvhqrzk
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-zdvhqrzk:ebddf6c59a0be20ff90ea6b54b4b67116c6c8508@sha256:a637025273893df5117c11b6ece9015534808adc9d4e1e711335a7b3b4333731
        name: container-image  
